services:
  public_service:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: public_service
    ports:
      - "8000:8000"
    environment:
      PRIVATE_SERVICE_URL: "http://private_service:8001"
    command: >
      poetry run uvicorn --factory app.main:create_app --host 0.0.0.0 --port 8000
    depends_on:
      - private_service
    networks:
      - app_network

  private_service:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: private_service
    environment:
      MINIO_URL: "http://minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
    command: >
      poetry run uvicorn --factory app.main:create_private_app --host 0.0.0.0 --port 8001
    depends_on:
      - minio
    networks:
      - app_network

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001" # Панель управления
    command: server --console-address ":9001" /data --certs-dir /certs
    volumes:
      - ./minio_data_docker:/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge